name: rlinwifi
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.12.8=h06a4308_0
  - certifi=2020.12.5=py36h06a4308_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.0.2u=h7b6447c_0
  - pip=20.3.3=py36h06a4308_0
  - python=3.6.5=hc3d631a_2
  - readline=7.0=h7b6447c_5
  - setuptools=51.0.0=py36h06a4308_2
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.11.0
    - astor==0.8.1
    - attrs==20.3.0
    - cached-property==1.5.2
    - chardet==4.0.0
    - cloudpickle==1.6.0
    - comet-git-pure==0.19.16
    - comet-ml==2.0.12
    - configobj==5.0.6
    - cycler==0.10.0
    - everett==1.0.3
    - future==0.18.2
    - gast==0.4.0
    - google-pasta==0.2.0
    - grpcio==1.34.0
    - gym==0.18.0
    - h5py==3.1.0
    - idna==2.10
    - importlib-metadata==3.3.0
    - jsonschema==3.2.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.3
    - matplotlib==3.3.3
    - netifaces==0.10.9
    - numpy==1.16.3
    - nvidia-ml-py3==7.352.0
    - pillow==7.2.0
    - protobuf==3.14.0
    - pyglet==1.5.0
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pyzmq==20.0.0
    - requests==2.25.1
    - scipy==1.5.4
    - six==1.15.0
    - tensorboard==1.14.0
    - tensorflow==1.14.0
    - tensorflow-estimator==1.14.0
    - termcolor==1.1.0
    - torch==0.4.1
    - torchvision==0.2.1
    - tqdm==4.35.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.2
    - websocket-client==0.57.0
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - wurlitzer==2.0.1
    - zipp==3.4.0
prefix: ./envs/rlinwifi
